openapi: 3.0.0
info:
  description: Documentation for MotoOto api
  version: 1.0.0
  title: "MotoOto"
# host: "localhost:8080"
# basePath: "/api"
tags:
  - name: auth
    description: auth endpoints
paths:
  /auth/login:
    post:
      tags:
        - auth
      requestBody:
        description: User credentials
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCredentials"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        '401':
          description: Unauthorized
  /auth/register:
    post:
      tags:
        - auth
      requestBody:
        description: Registration details
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDto"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
                example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        '409':
          description: User already exists
components:
  schemas:
    UserCredentials:
      type: object
      properties:
        username:
          type: string
          example: test@user.com
        password:
          type: string
          example: qwerty123
    UserDto:
      type: object
      properties:
        username:
          type: string
          example: newUser
        email:
          type: string
          example: new@user.com
        password:
          type: string
          example: qwerty123